# Generated by Django 3.2.10 on 2024-05-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_parsedpricesforitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedpricesforitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsings', to='store.item', verbose_name='Товар'),
        ),
    ]
